using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;

namespace OMEWizard
{
	/// <summary>
    /// Form for selecting parameter files within OMEWizard.
    /// </summary>
    public partial class ParamSelector : Form
    {
        /// <summary> Path to parameter file.</summary>        
        private string m_paramPath;
        /// <summary> Field for entering parameter path.</summary>        
        private TextBox paramPathField;
        /// <summary> Field for entering model name.</summary>        
        private TextBox modelNameField;
        /// <summary> Button for using file dialog to browse for parameter button.</summary>        
        private Button paramBrowseButton;
        /// <summary> Text label.</summary>        
        private Label label1;
        /// <summary> Text label.</summary>        
        private Label label2;
        /// <summary> Button for accepting parameter entry.</summary>        
        private Button OKButton;
        /// <summary> Button for cancelling parameter entry. </summary> 
        private Button CnclButton;
        /// <summary> The name of the targeted submodel.</summary>
        private string m_modelName;       

        public ParamSelector()
        {
            InitializeComponent();
        }

		/// <summary>
        /// Path to selected parameter file.
        /// </summary>
        public string ParamPath
        {
            get
            {
                return m_paramPath;
            }
        }

		/// <summary>
        /// Name of targeted submodel component.
        /// </summary>
        public string TargetModel
        {
            get
            {
                return m_modelName;
            }
        }
		
		/// <summary>
        /// Event handler for opening a file selection dialog for parameter file browsing.
        /// </summary>
        /// <param name="sender">The browse button.</param>
        /// <param name="e">The event generated by the button click.</param>
        private void paramBrowseButton_Click(object sender, EventArgs e)
        {
            OpenFileDialog oDlg = new OpenFileDialog();
            oDlg.FileName = Path.GetFileName(paramPathField.Text);
            oDlg.Filter = "Simile Files (*.spf)|*.spf|CSV Files (*.csv)|*.csv|All Files (*.*)|*.*";
            oDlg.FilterIndex = 3;
            oDlg.Multiselect = false;
            oDlg.Title = "Please select a parameter file to include";

            if (oDlg.ShowDialog() == DialogResult.OK)
            {
                paramPathField.Text = oDlg.FileName;
            }
        }

		/// <summary>
        /// Event generated by the Parameter dialog closing. The internal fields are
        /// populated based on how the dialog exits.
        /// </summary>
        /// <param name="sender">The dialog window (?).</param>
        /// <param name="e">The event information.</param>
        private void ParamSelector_FormClosing(object sender, FormClosingEventArgs e)
        {
            if(this.DialogResult==DialogResult.OK)
            {
                m_paramPath = paramPathField.Text;
                m_modelName = modelNameField.Text;
            }
            else
            {
                m_paramPath = "";
                m_modelName = "";
            }
        }

		/// <summary>
        /// Standard Winforms component initialization call. 
        /// </summary>
        private void InitializeComponent()
        {
            this.paramPathField = new System.Windows.Forms.TextBox();
            this.modelNameField = new System.Windows.Forms.TextBox();
            this.paramBrowseButton = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.OKButton = new System.Windows.Forms.Button();
            this.CnclButton = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // paramPathField
            // 
            this.paramPathField.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.paramPathField.Location = new System.Drawing.Point(12, 25);
            this.paramPathField.Name = "paramPathField";
            this.paramPathField.Size = new System.Drawing.Size(371, 20);
            this.paramPathField.TabIndex = 0;
            // 
            // modelNameField
            // 
            this.modelNameField.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.modelNameField.Location = new System.Drawing.Point(12, 64);
            this.modelNameField.Name = "modelNameField";
            this.modelNameField.Size = new System.Drawing.Size(371, 20);
            this.modelNameField.TabIndex = 1;
            // 
            // paramBrowseButton
            // 
            this.paramBrowseButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.paramBrowseButton.Location = new System.Drawing.Point(389, 23);
            this.paramBrowseButton.Name = "paramBrowseButton";
            this.paramBrowseButton.Size = new System.Drawing.Size(75, 23);
            this.paramBrowseButton.TabIndex = 2;
            this.paramBrowseButton.Text = "Browse";
            this.paramBrowseButton.UseVisualStyleBackColor = true;
            this.paramBrowseButton.Click += new System.EventHandler(this.paramBrowseButton_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(12, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(74, 13);
            this.label1.TabIndex = 3;
            this.label1.Text = "Parameter file:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(12, 48);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(108, 13);
            this.label2.TabIndex = 4;
            this.label2.Text = "Applied Model Name:";
            // 
            // OKButton
            // 
            this.OKButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.OKButton.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.OKButton.Location = new System.Drawing.Point(308, 90);
            this.OKButton.Name = "OKButton";
            this.OKButton.Size = new System.Drawing.Size(75, 23);
            this.OKButton.TabIndex = 5;
            this.OKButton.Text = "OK";
            this.OKButton.UseVisualStyleBackColor = true;
            // 
            // CancelButton
            // 
            this.CnclButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.CnclButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.CnclButton.Location = new System.Drawing.Point(389, 90);
            this.CnclButton.Name = "CancelButton";
            this.CnclButton.Size = new System.Drawing.Size(75, 23);
            this.CnclButton.TabIndex = 6;
            this.CnclButton.Text = "Cancel";
            this.CnclButton.UseVisualStyleBackColor = true;
            // 
            // ParamSelector
            // 
            this.AcceptButton = this.OKButton;
            this.CancelButton = this.CnclButton;
            this.ClientSize = new System.Drawing.Size(476, 127);
            this.Controls.Add(this.CnclButton);
            this.Controls.Add(this.OKButton);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.paramBrowseButton);
            this.Controls.Add(this.modelNameField);
            this.Controls.Add(this.paramPathField);
            this.Name = "ParamSelector";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.ParamSelector_FormClosing);
            this.ResumeLayout(false);
            this.PerformLayout();

        }
    }
}
